### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [DavidElwell/paul-laurence-dunbar_the-sport-of-the-gods#1]
- [x] Please run `se typogrify` and accept its changes
- [x] Upgrade your toolset version using `pipx upgrade standardebooks` and run `se lint` again. The latest version will find a few typos for you to fix. It will incorrectly flag a newspaper headline, but I think what we can do is remove the double quotes in that blockquote and change the single quotes to double quotes. It's obvious that it's a quotation given the formatting and context.
- [x] The colophon lists the publisher, but we don't list that. It should say `published in 1902 by<br/> <a..>Paul Laurence Dunbar</a>`.
- [x] In the colophon, your name needs `<b epub:type="z3998:personal-name">`
- [x] `ragtime` is sometimes quoted and capitalized, and sometimes not. I think we should normalize it to remove quotes and capitals because it's a common word now. You can do this in an `[Editorial]` commit.
- [x] `The <i>Universe</i> was yellow.` needs semantics, is that a newspaper?
- [x] In chapter 13 there's a letter with a salutation. You can use `<b epub:type="z3998:salutation">` to style that, as `<b>` is small caps by default in SE ebooks. Then, you can remove the salutation styling from the `local.css`.
- [x] dc:description in the metadata: This should be a single sentence in the active voice that describes the plot, not including the author's name. For example, `Bob Smith's novel about a Sam, a blacksmith, who goes on a trip` is *not* what we want. Rather, `A blacksmith goes on a journey to discover himself` is what we want.
- [x] Typo in the long description: `reUnited States`. Can you write a little more about what the novel is about, without spoilers? Introduce some characters, details about their struggle, themes, etc.?

**Comment by DavidElwell** [comment]
Lint found nothing. I activized the short description, but I kept the long description opaque, since the grim progress of the story isn't foreshadowed at the start.  Just about anything becomes a spoiler. "reUnited" was not a typo. Maybe I was being too cute about the shadow of the late rebellion.

**Comment by acabal** [comment]
Re. long description, that's OK, but what else can we say about the book? As it is right now, the long description barely says more than the short description. Are there important themes? Can you flesh out the family a little more? *Why* are they struggling? What has set them, and the plot, in motion?

**Comment by DavidElwell** [comment]
Let me add a little more. I think I can allude to southern prejudice and northern temptations, plus the cold grip of justice.

**Comment by DavidElwell** [comment]
The long description is now a little longer. I avoided saying what sets the plot in motion because that's the first surprise. Dunbar does an elegant job of setting up a quiet, well-ordered environment.
